packages:
  - "packages/@real-token/aa-modal"
  - "packages/@real-token/ui-components"
  - "packages/@real-token/web3"
  - "packages/@real-token/core"
  - "packages/@real-token/types"
  - "packages/@real-token/i18n-locales"
  - "packages/@real-token/mcp"
  - "apps/realtoken-commons-example"
