name: Release to npm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Utilise la version Node définie dans .nvmrc !
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
          scope: "@real-token"

      - name: Prepare .npmrc for GitHub Packages
        run: |
          echo "@real-token:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> .npmrc
          # echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          cat .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install PNPM (version from package.json)
        uses: pnpm/action-setup@v3
        with:
          run_install: false
          readPackageManager: "version"

      - name: Install dependencies
        run: pnpm install --filter "./packages/**"

      - name: Build packages
        run: pnpm run build:lib

      - name: Publish with Changesets
        run: pnpm changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tags on release
        if: success()
        run: git push --follow-tags origin main
